<base href="/public">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KEVES IN  & SUITES | PETTY CASH REPORT</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />

    <!-- Style CSS -->
    <link rel="stylesheet" href="{{asset('assets/pettycash/style.css')}}">
</head>
<body>

    <div class="main">
        <div>
            <img src="{{asset('assets/logo-2-1.png')}}" alt="KEVES INN & SUITES" width="100%" height="100PX" />
        </div>
        <div class="d-flex flex-row">
            <h2 class="col-md justify-content-center align-items-center text-center">PETTY CASH FROM : {{$data['start_date']}}  -  {{$data['end_date']}}</h1>
            <span><a class="btn btn-danger mb-2 flex-stretch" href="{{route('petty-cash.index')}}">Return Back</a></span>
        </div>
        
        <div class="row">
            <div class="added-product col-12">
                <div class="product-table">
                    <table class="table text-center table-responsive-md">
                        <thead class="bg-danger text-white fw-bold text-2xl">
                          <tr>
                            <th scope="col">TRANSACTION DATE</th>
                            <th scope="col">VOUCHERS NO</th>
                            <th scope="col-5">PARTICULARS</th>
                            <th scope="col">CASH IN  (<strike>N</strike>)</th>
                            <th scope="col">CASH OUT (<strike>N</strike>) </th>
                            <th scope="col">BALANCE  (<strike>N</strike>)</th>
                            <!-- <th scope="col">Action</th> -->
                          </tr>
                        </thead>
                        <tbody id="productTableBody">
                            <!-- Generated by Script -->
                            <tr>
                                <td>-</td>
                                <td>-</td>
                                <td>Balance Brought Froward</td>
                                <td>-</td>
                                <td>-</td>
                                <td>{{number_format($data['open_balance'],2)}}</td>
                              
                             </tr>
                            @foreach ($petty_reports as $pettycash)
                            <tr>
                                <td>{{$pettycash->transaction_date}}</td>
                                <td>{{$pettycash->voucher_no}}</td>
                                <td>{{$pettycash->particulars}}</td>
                                <td>{{number_format($pettycash->cash_in,2)}}</td>
                                <td>{{number_format($pettycash->cash_out,2)}}</td>
                                <td>{{number_format($pettycash->balance,2)}}</td>
                              
                             </tr>
                            @endforeach
                            <tr>
                                <td class="fw-bold 2.0rem"></td>
                                <td class="fw-bold 2.0rem"></td>
                                <td class="fw-bold 2.0rem">GRAND TOTAL</td>
                                <td class="fw-bold 2.0rem">{{number_format($data['cash_in_total'],2)}}</td>
                                <td class="fw-bold 2.0rem"> {{number_format($data['cash_out_total'],2)}}</td>
                                <td class="fw-bold 2.0rem">{{number_format($data['cl_bal'],2) }}</td>
                            </tr>
                        </tbody>
                    </table>
                    
                </div>

                <div class="table-footer row">
                    <p class="col-4">CLOSING BALANCE: <span id="totalAmount"><strike>N</strike> {{number_format($data['cl_bal'] ,2)}}</span></p>
                    
                    <button type="button" id="generateInvoice" class="btn btn-danger">Print</button>
                </div>
                
            </div>
        </div>
    </div>

    <!-- Invoice Modal -->
    <div class="modal fade" id="invoiceModal" tabindex="-1" role="dialog" aria-labelledby="invoiceModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="invoiceModalLabel">Invoice</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="invoice">
                        <div class="product-table">
                            <table class="table text-center">
                                <thead class="thead-dark">
                                <tr>
                                    <th scope="col">TRANSACTION DATE</th>
                                    <th scope="col">VOUCHERS NO</th>
                                    <th scope="col">PARTICULARS</th>
                                    <th scope="col">CASH IN  (<strike>N</strike>)</th>
                                    <th scope="col">CASH OUT (<strike>N</strike>) </th>
                                    <th scope="col">BALANCE  (<strike>N</strike>)</th>
                                    
                                </tr>
                                </thead>
                                    <tbody id="invoiceTableBody">
                                        <!-- Products will be populated here -->
                                        @foreach ($petty_reports as $pettycash)
                                        <tr>
                                            <td>{{$pettycash->transaction_date}}</td>
                                            <td>{{$pettycash->voucher_no}}</td>
                                            <td>{{$pettycash->particulars}}</td>
                                            <td>{{number_format($pettycash->cash_in,2)}}</td>
                                            <td>{{number_format($pettycash->cash_out,2)}}</td>
                                            <td>{{number_format($pettycash->balance,2)}}</td>  
                                        </tr>
                                        @endforeach
                                        <tr>
                                            <td class="fw-bold 2.0rem"></td>
                                            <td class="fw-bold 2.0rem"></td>
                                            <td class="fw-bold 2.0rem">GRAND TOTAL</td>
                                            <td class="fw-bold 2.0rem">{{number_format($data['cash_in_total'],2)}}</td>
                                            <td class="fw-bold 2.0rem"> {{number_format($data['cash_out_total'],2)}}</td>
                                            <td class="fw-bold 2.0rem">{{number_format($data['cl_bal'],2) }}</td>
                                        <!-- <td class="fw-bold 2.0rem"><strike>N</strike> {{number_format(($data['cash_in_total'] - $data['cash_out_total']),2)}}</td> -->
                                        </tr>
                                    </tbody>
                            </table>
                        </div>
                        <p class="ml-auto mr-5">Total: $<span id="invoiceTotal">0.00</span></p>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" id="printButton" class="btn btn-dark" data-dismiss="modal">Print</button>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"></script>

    <!-- Script JS -->
    <script src="asset('assets/dist/js/script.js')"></script>
</body>
</html>